name: dating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.4
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  http: ^1.2.2
  #Firebase
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  #Storage
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  #Localization
  easy_localization: ^3.0.4
  #Router
  go_router: ^15.1.2
  #DependcyInjection
  get_it: ^8.0.2
  injectable: ^2.3.5

  #State Management
  flutter_bloc: ^9.1.1
  #UI
  moon_extension: ^0.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.5.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/icons/
    - assets/images/
    - assets/localizable/

  
